# characters.py
from dataclasses import dataclass
from typing import List

@dataclass
class Character:
    slug: str
    name: str
    
    def __str__(self):
        return self.name
    
    def get_url(self):
        return f"https://ultimateframedata.com/{self.slug}"


# All characters as objects
CHARACTERS: List[Character] = [
    Character("banjo_and_kazooie", "Banjo & Kazooie"),
    Character("bayonetta", "Bayonetta"),
    Character("bowser", "Bowser"),
    Character("bowser_jr", "Bowser Jr."),
    Character("byleth", "Byleth"),
    Character("captain_falcon", "Captain Falcon"),
    Character("chrom", "Chrom"),
    Character("cloud", "Cloud"),
    Character("corrin", "Corrin"),
    Character("daisy", "Daisy"),
    Character("dark_pit", "Dark Pit"),
    Character("dark_samus", "Dark Samus"),
    Character("diddy_kong", "Diddy Kong"),
    Character("donkey_kong", "Donkey Kong"),
    Character("dr_mario", "Dr. Mario"),
    Character("duck_hunt", "Duck Hunt"),
    Character("falco", "Falco"),
    Character("fox", "Fox"),
    Character("ganondorf", "Ganondorf"),
    Character("greninja", "Greninja"),
    Character("hero", "Hero"),
    Character("ice_climbers", "Ice Climbers"),
    Character("ike", "Ike"),
    Character("incineroar", "Incineroar"),
    Character("inkling", "Inkling"),
    Character("isabelle", "Isabelle"),
    Character("jigglypuff", "Jigglypuff"),
    Character("joker", "Joker"),
    Character("kazuya", "Kazuya"),
    Character("ken", "Ken"),
    Character("king_dedede", "King Dedede"),
    Character("king_k_rool", "King K. Rool"),
    Character("kirby", "Kirby"),
    Character("link", "Link"),
    Character("little_mac", "Little Mac"),
    Character("lucario", "Lucario"),
    Character("lucas", "Lucas"),
    Character("lucina", "Lucina"),
    Character("luigi", "Luigi"),
    Character("mario", "Mario"),
    Character("marth", "Marth"),
    Character("mega_man", "Mega Man"),
    Character("meta_knight", "Meta Knight"),
    Character("mewtwo", "Mewtwo"),
    Character("mii_brawler", "Mii Brawler"),
    Character("mii_gunner", "Mii Gunner"),
    Character("mii_swordfighter", "Mii Swordfighter"),
    Character("minmin", "Min Min"),
    Character("mr_game_and_watch", "Mr. Game & Watch"),
    Character("mythra", "Mythra"),
    Character("ness", "Ness"),
    Character("olimar", "Olimar"),
    Character("pac_man", "Pac-Man"),
    Character("palutena", "Palutena"),
    Character("peach", "Peach"),
    Character("pichu", "Pichu"),
    Character("pikachu", "Pikachu"),
    Character("piranha_plant", "Piranha Plant"),
    Character("pit", "Pit"),
    Character("pt_squirtle", "Squirtle"),
    Character("pt_ivysaur", "Ivysaur"),
    Character("pt_charizard", "Charizard"),
    Character("pyra", "Pyra"),
    Character("richter", "Richter"),
    Character("ridley", "Ridley"),
    Character("rob", "R.O.B."),
    Character("robin", "Robin"),
    Character("rosalina_and_luma", "Rosalina & Luma"),
    Character("roy", "Roy"),
    Character("ryu", "Ryu"),
    Character("samus", "Samus"),
    Character("sephiroth", "Sephiroth"),
    Character("sheik", "Sheik"),
    Character("shulk", "Shulk"),
    Character("simon", "Simon"),
    Character("snake", "Snake"),
    Character("sonic", "Sonic"),
    Character("sora", "Sora"),
    Character("steve", "Steve"),
    Character("terry", "Terry"),
    Character("toon_link", "Toon Link"),
    Character("villager", "Villager"),
    Character("wario", "Wario"),
    Character("wii_fit_trainer", "Wii Fit Trainer"),
    Character("wolf", "Wolf"),
    Character("yoshi", "Yoshi"),
    Character("young_link", "Young Link"),
    Character("zelda", "Zelda"),
    Character("zero_suit_samus", "Zero Suit Samus"),
]